    [manager]

    keymap = [
    { on = [ "-" ], run = "ouch decompress $1", desc = "Decompress archive" },
    { on = [ "+" ], run = "ouch compress $@", desc = "Decompress archive" },

    { on = [ "v" ], run = [ "shell --block --confirm 'mpv --load-auto-profiles=no --loop \"$1\" &> /dev/null &'" 
    ], desc = "Open mpv without config" },

    { on = [ "c", "v" ],        run = [
      "shell --block --confirm '~/.config/yazi/scripts/cutvideo'",
    ], desc = "Cut video" },

    { on = [ "o", "k" ],        run = [
      "shell --block --confirm 'zpool import -lf -R /run/media/sorath Krampus'",
      "cd /run/media/sorath/Krampus",
    ],  desc = "Open Krampus Zfs" },

    { on = [ "n", "f" ],        run = [
      "shell --block --confirm 'sudo mount /media/Bunker/Vault'",
      "shell --block --confirm 'sudo mount /media/Bunker/Crypta'",
    "cd /media/Bunker",
    ],  desc = "Open Bunker Nfs" },

    { on = [ "a", "a" ],    run = [ "shell --interactive --block 'mkdir '" ],               desc = "Create a directory" },

    { on = [ "o", "l" ],    run = [ "plugin zfs-open" ],               desc = "Open zfs pool and jump to a directory" },

    { on = [ "<", "<" ],    run = [ "plugin fuzzy" ],               desc = "Jump to a directory, or reveal a file using fzf" },

    { on = [ "<", "z" ],        run = [
      "shell --block --confirm '/nix/store/h0cn28h7mvkj1vwbdj4zkzkailkwr1i0-helix-24.03/bin/hx $(fd . ~/.config/LegionX --max-depth 4 --type f | /nix/store/aflkybxcxzm4fxnan2fg9z4d8dyd4qnb-fzf-0.52.1/bin/fzf --height 100%)'",
      "cd ~/.config/LegionX",
    ],  desc = "Edit home-manager files" },

    { on = [ "c", "p" ], run = [ 
      "shell --block --confirm '/nix/store/rn37a2vii9bkmbkj06s325g46yxd2k8y-dunst-1.11.0/bin/dunstify -t 1000 \"Path copied\"'", 
      "copy path"
    ], desc = "Copy the absolute path" },

    { on = [ "c", "d" ], run = [ 
      "shell --block --confirm '/nix/store/rn37a2vii9bkmbkj06s325g46yxd2k8y-dunst-1.11.0/bin/dunstify -t 1000 \"Parent path copied\"'", 
      "copy dirname"
    ], desc = "Copy the parent path" },

    { on = [ "c", "f" ], run = [ 
      "shell --block --confirm '/nix/store/rn37a2vii9bkmbkj06s325g46yxd2k8y-dunst-1.11.0/bin/dunstify -t 1000 \"Name of the file copied\"'", 
      "copy filename"
    ], desc = "Copy the name of the file" },

    { on = [ "c", "n" ], run = [ 
      "shell --block --confirm '/nix/store/rn37a2vii9bkmbkj06s325g46yxd2k8y-dunst-1.11.0/bin/dunstify -t 1000 \"Name of the file -ext copied\"'", 
      "copy name_without_ext"
    ], desc = "Copy the name of the file without ext" },

    { on = [ "*" ], run = [ 
      "shell --block --confirm 'chmod +x $1'",
      "shell --block --confirm 'dunstify -t 1000 \"Set executable!\" -i ~/.icons/dunst/terminal.png'",
    ],  desc = "chmod file" },

    { on = [ "º" ],             run = "shell --block --confirm '/nix/store/46jna9h25khan7lj0yg5s31ik2rbpfdd-gitui-0.26.3/bin/gitui'",  desc = "open Gitui" },
    { on = [ "ª" ],             run = "shell --block --confirm '/nix/store/hicqk4km5s1kix48pvm1pc7l2cg5ps73-ncdu-2.4/bin/ncdu'",  desc = "open Ncdu" },
    { on = [ "b", "g" ],        run = "shell --block --confirm '/nix/store/amcf183abxshjr7sva1lmbcjcll1y0jd-swaybg-1.2.1/bin/swaybg -m fill -i $1 &> /dev/null &'",  desc = "Set background" },
    { on = [ "b", "i" ],        run = "shell --block --confirm 'sudo dd if=$1 of=/dev/sdb'",  desc = "Write iso to a usbdrive" },
    { on = [ "d", "d" ],        run = "shell --block --confirm '/nix/store/pmrq09ip8yx2r0288cf0l1gnkfx86r7n-trash-cli-0.24.4.17/bin/trash-put \"$@\"'", desc = "Move the files to the trash" },
    { on = [ "D" ],         run = [ "remove --permanently", "escape --visual --select" ], desc = "Permanently delete the files" },
    { on = [ "d", "r" ],        run = "shell --block --confirm 'conceal restore'", desc = "Restore files from trash" },
    { on = [ "d", "a" ],        run = "shell --block --confirm '/nix/store/pmrq09ip8yx2r0288cf0l1gnkfx86r7n-trash-cli-0.24.4.17/bin/trash-empty -f; paplay ~/.sounds/trash-empty.ogg'", desc = "Clean All files from trash" },
    { on = [ "d", "c" ],        run = "shell --block --confirm 'conceal clean; paplay ~/.sounds/trash-empty.ogg'", desc = "Clean local files from trash" },

    { on = [ "o", "n" ],        run = [
    "shell --block --confirm 'mount /media/Bunker/Vault; mount /media/Bunker/Crypta'",
    "cd /media/Bunker", ],     desc = "Mount NFS" },

    { on = [ "<Esc>" ], run = "escape",  desc = "Exit visual mode, clear selected, or cancel search" },
    { on = [ "w" ],     run = "quit --no-cwd-file",    desc = "Exit the process" },
    { on = [ "q" ],     run = "quit",    desc = "Exit the process" },
    { on = [ "<C-q>" ], run = "close",   desc = "Close the current tab, or quit if it is last tab" },
    { on = [ "<C-z>" ], run = "suspend", desc = "Suspend the process" },

    # Navigation
    { on = [ "k" ], run = "arrow -1", desc = "Move cursor up" },
    { on = [ "j" ], run = "arrow 1",  desc = "Move cursor down" },

    { on = [ "K" ], run = "arrow -5", desc = "Move cursor up 5 lines" },
    { on = [ "J" ], run = "arrow 5",  desc = "Move cursor down 5 lines" },

    { on = [ "h" ], run = "leave", desc = "Go back to the parent directory" },
    { on = [ "l" ], run = "enter", desc = "Enter the child directory" },

    { on = [ "<C-Left>" ], run = "back",    desc = "Go back to the previous directory" },
    { on = [ "<C-Right>" ], run = "forward", desc = "Go forward to the next directory" },
    { on = [ "<C-Down>" ], run = "back",    desc = "Go back to the previous directory" },
    { on = [ "<C-Up>" ], run = "forward", desc = "Go forward to the next directory" },

    { on = [ "<C-k>" ], run = "peek -5", desc = "Peek up 5 units in the preview" },
    { on = [ "<C-j>" ], run = "peek 5",  desc = "Peek down 5 units in the preview" },

    { on = [ "<Up>" ],    run = "arrow -1", desc = "Move cursor up" },
    { on = [ "<Down>" ],  run = "arrow 1",  desc = "Move cursor down" },
    { on = [ "<Left>" ],  run = "leave",    desc = "Go back to the parent directory" },
    { on = [ "<Right>" ], run = [ "plugin --sync smart-enter" ],    desc = "Enter the child directory, or open file" },

    { on = [ "g", "g" ], run = "arrow -99999999", desc = "Move cursor to the top" },
    { on = [ "G" ],      run = "arrow 99999999",  desc = "Move cursor to the bottom" },

    # Selection
    { on = [ "<Space>" ], run = [ "select --state=none", "arrow 1" ], desc = "Toggle the current selection state" },
    # { on = [ "v" ],       run = "visual_mode",                        desc = "Enter visual mode (selection mode)" },
    { on = [ "V" ],       run = "visual_mode --unset",                desc = "Enter visual mode (unset mode)" },
    { on = [ "<C-a>" ],   run = "select_all --state=true",            desc = "Select all files" },
    { on = [ "<C-Space>" ],   run = "select_all --state=none",            desc = "Inverse selection of all files" },

    # Operation
    # { on = [ "o" ],         run = "open",                   desc = "Open the selected files" },
    { on = [ "O" ],         run = "open --interactive",     desc = "Open the selected files interactively" },
    { on = [ "<Enter>" ],   run = "open",                   desc = "Open the selected files" },
    { on = [ "<Enter>" ],   run = "open",                   desc = "Open the selected files" },
    { on = [ "<C-Enter>" ], run = "open --interactive",     desc = "Open the selected files interactively" },  # It's cool if you're using a terminal that supports CSI u
    { on = [ "y" ],         run = "yank",                   desc = "Copy the selected files" },
    { on = [ "x" ],         run = "yank --cut",             desc = "Cut the selected files" },
    { on = [ "p" ],         run = "paste",                  desc = "Paste the files" },
    { on = [ "P" ],         run = "paste --force",          desc = "Paste the files (overwrite if the destination exists)" },
    { on = [ "k" ],         run = "paste --follow",         desc = "Paste the files (follow the symlinks)" },
    { on = [ "K" ],         run = "paste --follow --force", desc = "Paste the files (overwrite + follow)" },
    # { on = [ "D" ],         run = "remove --permanently",   desc = "Permanently delete the files" },
    { on = [ "a", "z" ],         run = "create",                 desc = "Create a file or directory (ends with / for directories)" },
    { on = [ "r" ],         run = "rename",                 desc = "Rename a file or directory" },
    { on = [ ";" ],         run = "shell --interactive",                  desc = "Run a shell command" },
    { on = [ ":" ],         run = "shell --block --interactive",          desc = "Run a shell command (block the UI until the command finishes)" },
    { on = [ "." ],         run = "hidden toggle",          desc = "Toggle the visibility of hidden files" },
    { on = [ "s" ],         run = "search fd",              desc = "Search files by name using fd" },
    { on = [ "S" ],         run = "search rg --no-hidden",              desc = "Search files by content using ripgrep" },
    { on = [ "<C-s>" ],     run = "search none",            desc = "Cancel the ongoing search" },
    { on = [ "z" ],         run = "plugin zoxide",            desc = "Jump to a directory using zoxide" },

    # Linemode
    { on = [ "m", "s" ], run = "linemode size",        desc = "Set linemode to size" },
    { on = [ "m", "p" ], run = "linemode permissions", desc = "Set linemode to permissions" },
    { on = [ "m", "m" ], run = "linemode mtime",       desc = "Set linemode to mtime" },
    { on = [ "m", "n" ], run = "linemode none",        desc = "Set linemode to none" },

    # Find
    { on = [ "/" ], run = "find" },
    { on = [ "?" ], run = "find --previous" },
    { on = [ "n" ], run = "find_arrow" },
    { on = [ "N" ], run = "find_arrow --previous" },
    { on = [ "-" ],         run = "link",                   desc = "Symlink the absolute path of files" },
    { on = [ "_" ],         run = "link --relative",        desc = "Symlink the relative path of files" },

    # Sorting
    { on = [ ",", "a" ], run = "sort alphabetical --dir_first",           desc = "Sort alphabetically, directories first" },
    { on = [ ",", "A" ], run = "sort alphabetical --reverse --dir_first", desc = "Sort alphabetically, directories first (reverse)" },
    { on = [ ",", "c" ], run = "sort created --dir_first",                desc = "Sort by creation time, directories first" },
    { on = [ ",", "C" ], run = "sort created --reverse --dir_first",      desc = "Sort by creation time, directories first (reverse)" },
    { on = [ ",", "m" ], run = "sort modified --dir_first",               desc = "Sort by modified time, directories first" },
    { on = [ ",", "M" ], run = "sort modified --reverse --dir_first",     desc = "Sort by modified time, directories first (reverse)" },
    { on = [ ",", "n" ], run = "sort natural --dir_first",                desc = "Sort naturally, directories first" },
    { on = [ ",", "N" ], run = "sort natural --reverse --dir_first",      desc = "Sort naturally, directories first (reverse)" },
    { on = [ ",", "s" ], run = "sort size --dir_first",                   desc = "Sort by size, directories first" },
    { on = [ ",", "S" ], run = "sort size --reverse --dir_first",         desc = "Sort by size, directories first (reverse)" },
    { on = [ ",", "e" ], run = "sort extension --dir_first",         	   desc = "Sort by extension" },
	  { on = [ ",", "E" ], run = "sort extension --reverse --dir_first",    desc = "Sort by extension (reverse)" },

    # Tabs
    { on = [ "t" ], run = "tab_create --current", desc = "Create a new tab using the current path" },

    { on = [ "1" ], run = "tab_switch 0", desc = "Switch to the first tab" },
    { on = [ "2" ], run = "tab_switch 1", desc = "Switch to the second tab" },
    { on = [ "3" ], run = "tab_switch 2", desc = "Switch to the third tab" },
    { on = [ "4" ], run = "tab_switch 3", desc = "Switch to the fourth tab" },
    { on = [ "5" ], run = "tab_switch 4", desc = "Switch to the fifth tab" },
    { on = [ "6" ], run = "tab_switch 5", desc = "Switch to the sixth tab" },
    { on = [ "7" ], run = "tab_switch 6", desc = "Switch to the seventh tab" },
    { on = [ "8" ], run = "tab_switch 7", desc = "Switch to the eighth tab" },
    { on = [ "9" ], run = "tab_switch 8", desc = "Switch to the ninth tab" },

    { on = [ "[" ], run = "tab_switch -1 --relative", desc = "Switch to the previous tab" },
    { on = [ "]" ], run = "tab_switch 1 --relative",  desc = "Switch to the next tab" },

    { on = [ "{" ], run = "tab_swap -1", desc = "Swap the current tab with the previous tab" },
    { on = [ "}" ], run = "tab_swap 1",  desc = "Swap the current tab with the next tab" },

    # Tasks
    { on = [ "T" ], run = "tasks_show", desc = "Show the tasks manager" },

    # Goto
    { on = [ "g", "h" ],       run = "cd ~",                       desc = "Go to the home directory" },
    { on = [ "g", "c" ],       run = "cd ~/.config",               desc = "Go to the config directory" },
    { on = [ "g", "." ],       run = "cd ~/.config/LegionX",               desc = "Go to the config directory" },
    { on = [ "g", "l" ],       run = "cd ~/.local",                desc = "Go to the local directory" },
    { on = [ "g", "d" ],       run = "cd ~/Documentos",            desc = "Go to the Documentos directory" },
    { on = [ "g", "i" ],       run = "cd ~/Imagens",               desc = "Go to the Imagens directory" },
    { on = [ "g", "v" ],       run = "cd ~/Vídeos",                desc = "Go to the Vídeos directory" },
    { on = [ "g", "t" ],       run = "cd ~/Transferências",         desc = "Go to the Transferências directory" },
    { on = [ "g", "L" ],       run = "cd /run/media/sorath/Legion",  desc = "Go to Legion" },
    { on = [ "g", "M" ],       run = "cd /run/media/sorath",  desc = "Go to Legion" },
    { on = [ "g", "x" ],       run = "cd ~/.password-store",  desc = "Go to pw" },
    { on = [ "g", "<Space>" ], run = "cd --interactive",           desc = "Go to a directory interactively" },

    # Help
    { on = [ "~" ], run = "help", desc = "Open help" },
    ]

    [tasks]

    keymap = [
    { on = [ "<Esc>" ], run = "close", desc = "Hide the task manager" },
    { on = [ "<C-q>" ], run = "close", desc = "Hide the task manager" },
    { on = [ "w" ],     run = "close", desc = "Hide the task manager" },

    { on = [ "k" ], run = "arrow -1", desc = "Move cursor up" },
    { on = [ "j" ], run = "arrow 1",  desc = "Move cursor down" },

    { on = [ "<Up>" ],   run = "arrow -1", desc = "Move cursor up" },
    { on = [ "<Down>" ], run = "arrow 1",  desc = "Move cursor down" },

    { on = [ "<Enter>" ], run = "inspect", desc = "Inspect the task" },
    { on = [ "x" ],       run = "cancel",  desc = "Cancel the task" },

    { on = [ "~" ], run = "help", desc = "Open help" }
    ]

    [select]

    keymap = [
    { on = [ "<C-q>" ],   run = "close",          desc = "Cancel selection" },
    { on = [ "<Esc>" ],   run = "close",          desc = "Cancel selection" },
    { on = [ "<Enter>" ], run = "close --submit", desc = "Submit the selection" },

    { on = [ "k" ], run = "arrow -1", desc = "Move cursor up" },
    { on = [ "j" ], run = "arrow 1",  desc = "Move cursor down" },

    { on = [ "K" ], run = "arrow -5", desc = "Move cursor up 5 lines" },
    { on = [ "J" ], run = "arrow 5",  desc = "Move cursor down 5 lines" },

    { on = [ "<Up>" ],   run = "arrow -1", desc = "Move cursor up" },
    { on = [ "<Down>" ], run = "arrow 1",  desc = "Move cursor down" },

    { on = [ "~" ], run = "help", desc = "Open help" }
    ]

    [input]

    keymap = [
    { on = [ "<C-q>" ],       run = "close",          desc = "Cancel input" },
    { on = [ "<Enter>" ],     run = "close --submit", desc = "Submit the input" },
    { on = [ "<Esc>" ],       run = "escape",         desc = "Go back the normal mode, or cancel input" },

    { on = [ "<Backspace>" ], run = "backspace" },

    # Mode
    { on = [ "i" ], run = "insert",                              desc = "Enter insert mode" },
    { on = [ "a" ], run = "insert --append",                     desc = "Enter append mode" },
    { on = [ "v" ], run = "visual",                              desc = "Enter visual mode" },
    { on = [ "V" ], run = [ "move -999", "visual", "move 999" ], desc = "Enter visual mode and select all" },

    # Navigation
    { on = [ "h" ], run = "move -1", desc = "Move cursor left" },
    { on = [ "l" ], run = "move 1",  desc = "Move cursor right" },

    { on = [ "0" ], run = "move -999",                       desc = "Move to the BOL" },
    { on = [ "$" ], run = "move 999",                        desc = "Move to the EOL" },
    { on = [ "I" ], run = [ "move -999", "insert" ],         desc = "Move to the BOL, and enter insert mode" },
    { on = [ "A" ], run = [ "move 999", "insert --append" ], desc = "Move to the EOL, and enter append mode" },

    { on = [ "<Left>" ],  run = "move -1", desc = "Move cursor left" },
    { on = [ "<Right>" ], run = "move 1",  desc = "Move cursor right" },

    { on = [ "b" ], run = "backward",              desc = "Move to the beginning of the previous word" },
    { on = [ "w" ], run = "forward",               desc = "Move to the beginning of the next word" },
    { on = [ "e" ], run = "forward --end-of-word", desc = "Move to the end of the next word" },

    # Deletion
    { on = [ "d" ], run = "delete --cut",                              desc = "Cut the selected characters" },
    { on = [ "D" ], run = [ "delete --cut", "move 999" ],              desc = "Cut until the EOL" },
    { on = [ "c" ], run = "delete --cut --insert",                     desc = "Cut the selected characters, and enter insert mode" },
    { on = [ "C" ], run = [ "delete --cut --insert", "move 999" ],     desc = "Cut until the EOL, and enter insert mode" },
    { on = [ "x" ], run = [ "delete --cut", "move 1 --in-operating" ], desc = "Cut the current character" },

    # Yank/Paste
    { on = [ "y" ], run = "yank",           desc = "Copy the selected characters" },
    { on = [ "p" ], run = "paste",          desc = "Paste the copied characters after the cursor" },
    { on = [ "P" ], run = "paste --before", desc = "Paste the copied characters before the cursor" },

    # Undo/Redo
    { on = [ "u" ],     run = "undo", desc = "Undo the last operation" },
    { on = [ "<C-r>" ], run = "redo", desc = "Redo the last operation" },

    # Help
    { on = [ "~" ], run = "help", desc = "Open help" }
    ]

    [help]

    keymap = [
    { on = [ "<Esc>" ], run = "escape", desc = "Clear the filter, or hide the help" },
    { on = [ "q" ],     run = "close",  desc = "Exit the process" },
    { on = [ "<C-q>" ], run = "close",  desc = "Hide the help" },

    # Navigation
    { on = [ "k" ], run = "arrow -1", desc = "Move cursor up" },
    { on = [ "j" ], run = "arrow 1",  desc = "Move cursor down" },

    { on = [ "K" ], run = "arrow -5", desc = "Move cursor up 5 lines" },
    { on = [ "J" ], run = "arrow 5",  desc = "Move cursor down 5 lines" },

    { on = [ "<Up>" ],   run = "arrow -1", desc = "Move cursor up" },
    { on = [ "<Down>" ], run = "arrow 1",  desc = "Move cursor down" },

    # Filtering
    { on = [ "/" ], run = "filter", desc = "Apply a filter for the help items" },
    ]
